# version: v0.1.2
# metadata -- add as many key/value pairs as you want
[metadata]
org = "orgX"
maintainer = "k8s-admin"

# paths to the certificate for connecting to the cluster
# You can skip this if you use Helmsman on a machine with kubectl already connected to your k8s cluster. 
# you have to use exact key names here : 'caCrt' for certificate and 'caKey' for the key
[certificates]
# caCrt = "s3://mybucket/ca.crt" # s3 bucket path, or valid local file relative path
# caKey = "../ca.key" 

[settings]
kubeContext = "minikube" # will try connect to this context first, if it does not exist, it will be created using the details below
# username = "admin"
# password = "$PASSWORD" # the name of an environment variable containing the k8s password
# clusterURI = "https://192.168.99.100:8443" # cluster API


# define your environments and thier k8s namespaces
# syntax: environment_name = "k8s_namespace"
[namespaces]
staging = "staging" 
production = "default"


# define any private/public helm charts repos you would like to get charts from
# syntax: repo_name = "repo_url"
# only private repos hosted in s3 buckets are now supported
[helmRepos]
stable = "https://kubernetes-charts.storage.googleapis.com"
incubator = "http://storage.googleapis.com/kubernetes-charts-incubator"
#myrepo = "s3://my-private-repo/charts"

# define the desired state of your applications helm charts
# each contains the following:


[apps]

    [apps.jenkins]
    name = "jenkins" # should be unique across all apps
    description = "jenkins"
    namespace = "staging" # maps to the namespace as defined in environmetns above
    enabled = true # change to false if you want to delete this app release [empty = flase]
    chart = "stable/jenkins" # changing the chart name means delete and recreate this chart
    version = "0.9.1" # chart version
    valuesFile = "" # leaving it empty uses the default chart values
    purge = false # will only be considered when there is a delete operation
    test = false # run the tests when this release is installed for the first time only
    # [apps.jenkins.set] # values to override values from values.yaml with values from env vars-- useful for passing secrets to charts
    #     db_username="$DB_USERNAME"
    #     db_password="$DB_PASSWORD"


    [apps.artifactory]
    name = "artifactory" # should be unique across all apps
    description = "artifactory"
    namespace = "staging" # maps to the namespace as defined in environmetns above
    enabled = true # change to false if you want to delete this app release [empty = flase]
    chart = "stable/artifactory" # changing the chart name means delete and recreate this chart
    version = "6.2.0" # chart version
    valuesFile = "" # leaving it empty uses the default chart values
    purge = false # will only be considered when there is a delete operation
    test = false # run the tests when this release is installed for the first time only
    # [apps.artifactory.set] # values to override values from values.yaml with values from env vars-- useful for passing secrets to charts
    #     db_username="$DB_USERNAME"
    #     db_password="$DB_PASSWORD"
