# version: v1.0.0
# metadata -- add as many key/value pairs as you want
[metadata]
org = "example.com"
maintainer = "k8s-admin (me@example.com)"
description = "example Desired State File for demo purposes."

# paths to the certificate for connecting to the cluster
# You can skip this if you use Helmsman on a machine with kubectl already connected to your k8s cluster. 
# you have to use exact key names here : 'caCrt' for certificate and 'caKey' for the key and caClient for the client certififcate
[certificates]
#caClient = "gs://mybucket/client.crt" # GCS bucket path
#caCrt = "s3://mybucket/ca.crt" # S3 bucket path 
#caKey = "../ca.key" # valid local file relative path

[settings]
kubeContext = "minikube" # will try connect to this context first, if it does not exist, it will be created using the details below
#username = "admin"
#password = "$K8S_PASSWORD" # the name of an environment variable containing the k8s password
#clusterURI = "$K8S_URI" # the name of an environment variable containing the cluster API
##clusterURI = "https://192.168.99.100:8443" # equivalent to the above

# define your environments and thier k8s namespaces
# syntax: 
# [namespaces.<your namespace>] -- whitespace before this entry does not matter, use whatever indentation style you like 
 # protected = <true or false> -- default to false 
[namespaces]
  [namespaces.staging]
  protected = false
  [namespaces.production]
  prtoected = true


# define any private/public helm charts repos you would like to get charts from
# syntax: repo_name = "repo_url"
# only private repos hosted in s3 buckets are now supported
[helmRepos]
stable = "https://kubernetes-charts.storage.googleapis.com"
incubator = "http://storage.googleapis.com/kubernetes-charts-incubator"
#myS3repo = "s3://my-S3-private-repo/charts"
#myGCSrepo = "gs://my-GCS-private-repo/charts"

# define the desired state of your applications helm charts
# each contains the following:


[apps]

    [apps.jenkins]
    name = "jenkins" # should be unique across all apps
    description = "jenkins"
    namespace = "staging" # maps to the namespace as defined in environmetns above
    enabled = true # change to false if you want to delete this app release [empty = flase]
    chart = "stable/jenkins" # changing the chart name means delete and recreate this chart
    version = "0.9.1" # chart version
    valuesFile = "" # leaving it empty uses the default chart values
    purge = false # will only be considered when there is a delete operation
    test = false # run the tests when this release is installed for the first time only
    prtoected = true
    # [apps.jenkins.set] # values to override values from values.yaml with values from env vars-- useful for passing secrets to charts
    #     db_username="$DB_USERNAME"
    #     db_password="$DB_PASSWORD"


    [apps.artifactory]
    name = "artifactory" # should be unique across all apps
    description = "artifactory"
    namespace = "staging" # maps to the namespace as defined in environmetns above
    enabled = true # change to false if you want to delete this app release [empty = flase]
    chart = "stable/artifactory" # changing the chart name means delete and recreate this chart
    version = "6.2.0" # chart version
    valuesFile = "" # leaving it empty uses the default chart values
    purge = false # will only be considered when there is a delete operation
    test = false # run the tests when this release is installed for the first time only
    # [apps.artifactory.set] # values to override values from values.yaml with values from env vars-- useful for passing secrets to charts
    #     db_username="$DB_USERNAME"
    #     db_password="$DB_PASSWORD"
