version: 2
jobs:
  build:
    docker:
      - image: docker:19.03.5-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker pull praqma/helmsman:latest
            docker build --cache-from=praqma/helmsman:latest -t helmsman .

  release:
    working_directory: "/tmp/go/src/helmsman"
    machine: true
    steps:
      - checkout
      - run:
          name: release helmsman
          command: |
            echo "releasing ..."
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            make build
            curl -sL https://git.io/goreleaser | bash -s -- --release-notes release-notes.md --rm-dist

      - run:
          name: build docker images and push them to dockerhub
          command: |
            TAG=$(git describe --abbrev=0 --tags)
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t praqma/helmsman:$TAG-helm-v3.0.2 --build-arg HELM_VERSION=v3.0.2 . --no-cache
            docker push praqma/helmsman:$TAG-helm-v3.0.2

workflows:
  version: 2
  build-test-push-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
