## This is a minimal example.
## It will use your current kube context and will deploy Tiller without RBAC service account.
## For the full config spec and options, check https://github.com/Praqma/helmsman/blob/master/docs/desired_state_specification.md

[helmRepos]
  stable = "https://kubernetes-charts.storage.googleapis.com"

[namespaces]
  [namespaces.staging]

[apps]
  [apps.jenkins]
    namespace = "staging"
    enabled = true
    chart = "stable/jenkins"
    version = "1.9.12"

  [apps.artifactory]
    namespace = "staging"
    enabled = true
    chart = "stable/artifactory"
    version = "7.3.1"
